### ISSUE TITLE
newcommentdata数据格式？

### ISSUE THREAD

**Issue by Yvonneyoung123** [yangqunfeng/doubanBookComment#1]
请问newcommentdata文件格式是什么？数据是否是utf-8 encoding？

**Comment by yangqunfeng** [comment]
文件格式是Python的pickle序列化文件，经过实验可以通过以下方式打开
`import pandas as pd`
`newBookInformation = pd.read_pickle("./newBookInformation")`
`df = pd.DataFrame(newBookInformation )`
打开即为DataFrame类型
想要保存为csv文件可以通过这行代码保存
`df.to_csv("./newBookInformation.csv",index=False)`

数据应该是gb2312编码，不太确定
